# Generated by Django 3.2.4 on 2021-06-03 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0003_receita_publicada'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='imagem_receita',
            field=models.ImageField(blank=True, upload_to='img/%d/%m/%Y/'),
        ),
    ]
