# Generated by Django 3.2.4 on 2021-06-03 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0004_receita_imagem_receita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='imagem_receita',
            field=models.ImageField(blank=True, upload_to='imagem/%d/%m/%Y/'),
        ),
    ]
